update

diff --git a/.github/workflows/test-native.yml b/.github/workflows/test-native.yml
--- a/.github/workflows/test-native.yml
+++ b/.github/workflows/test-native.yml
@@ -76,6 +76,7 @@ jobs:
 
       - name: Install Maestro
         uses: ./.github/actions/install-maestro
+        id: install-maestro
 
       - name: Wait for Dev Server to Be Ready
         run: node scripts/start-dev-server.mjs --check-only
@@ -118,25 +119,26 @@ jobs:
             ${{ env.test_app_path }}/dev-server.log
 
       - name: Prepare Maestro Logs
-        if: ${{ always() }}
+        id: prepare-maestro-logs
+        if: ${{ always() && steps.install-maestro.outcome == 'success' }}
         continue-on-error: true
         run: cp -r "$HOME/.maestro/tests" maestro-logs
 
       - name: Upload Maestro Logs
         uses: actions/upload-artifact@v4.3.1
-        if: ${{ always() }}
+        if: ${{ always() && steps.prepare-maestro-logs.outcome == 'success' }}
         continue-on-error: true
         with:
-          name: dev-maestro-logs
+          name: release-maestro-logs
           path: |
             ${{ env.test_app_path }}/maestro-logs
 
       - name: Upload Maestro Screenshots
         uses: actions/upload-artifact@v4.3.1
-        if: ${{ always() }}
+        if: ${{ always() && steps.install-maestro.outcome == 'success' }}
         continue-on-error: true
         with:
-          name: dev-maestro-screenshots
+          name: release-maestro-screenshots
           path: |
             ${{ env.test_app_path }}/maestro-screenshots
 
@@ -195,6 +197,7 @@ jobs:
         run: xcrun simctl boot $SIMULATOR_UDID
 
       - name: Install Maestro
+        id: install-maestro
         uses: ./.github/actions/install-maestro
 
       - name: Patch Packages
@@ -232,6 +235,14 @@ jobs:
         run: |
           cp -r test-bundle-output/. ${{ github.workspace }}/${{ needs.build-ios-test-app.outputs.built-app-path }}/
 
+      - name: Check .app
+        id: check-app
+        run: |
+          if [ ! -e ${{ github.workspace }}/${{ needs.build-ios-test-app.outputs.built-app-path }} ]; then
+            echo "Error: .app not found"
+            exit 1
+          fi
+
       - name: Install App in Simulator
         env:
           SIMULATOR_UDID: ${{ steps.get-simulator-udid.outputs.simulator_udid }}
@@ -247,8 +258,7 @@ jobs:
 
       - name: Upload App
         uses: actions/upload-artifact@v4.3.1
-        # Only upload if the test failed to save space
-        if: ${{ failure() }}
+        if: ${{ always() && steps.check-app.outcome == 'success' }}
         continue-on-error: true
         with:
           name: release-app
@@ -256,13 +266,14 @@ jobs:
             path: ${{ needs.build-ios-test-app.outputs.built-app-path }}
 
       - name: Prepare Maestro Logs
-        if: ${{ always() }}
+        id: prepare-maestro-logs
+        if: ${{ always() && steps.install-maestro.outcome == 'success' }}
         continue-on-error: true
         run: cp -r "$HOME/.maestro/tests" maestro-logs
 
       - name: Upload Maestro Logs
         uses: actions/upload-artifact@v4.3.1
-        if: ${{ always() }}
+        if: ${{ always() && steps.prepare-maestro-logs.outcome == 'success' }}
         continue-on-error: true
         with:
           name: release-maestro-logs
@@ -271,7 +282,7 @@ jobs:
 
       - name: Upload Maestro Screenshots
         uses: actions/upload-artifact@v4.3.1
-        if: ${{ always() }}
+        if: ${{ always() && steps.install-maestro.outcome == 'success' }}
         continue-on-error: true
         with:
           name: release-maestro-screenshots
